-- La Taverna - Supabase schema
-- Incolla tutto questo file nel Supabase SQL Editor e premi Run.

create table if not exists public.dnd_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id) on delete cascade,
    system_id text not null default 'dnd5e',
    name text not null,
    status text not null default 'attiva',
    party_level integer not null default 1,
    next_date text default '',
    map_url text default '',
    description text default '',
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.dnd_sessions
    add column if not exists system_id text not null default 'dnd5e',
    add column if not exists share_code text unique,
    add column if not exists share_enabled boolean not null default false;

create table if not exists public.user_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default 'Viandante',
    title text not null default 'Viandante della Taverna',
    avatar_url text default '',
    accent text not null default 'amethyst',
    glow boolean not null default true,
    compact_cards boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
    user_id uuid not null references auth.users(id) on delete cascade,
    key text not null,
    value jsonb not null default 'null'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    primary key (user_id, key)
);

create table if not exists public.characters (
    id bigint generated by default as identity primary key,
    user_id uuid references auth.users(id) on delete cascade,
    system_id text default 'dnd5e',
    name text not null default '',
    class text default '',
    level integer not null default 1,
    hp integer default 10,
    hp_max integer default 10,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table public.characters
    add column if not exists user_id uuid references auth.users(id) on delete cascade,
    add column if not exists system_id text default 'dnd5e',
    add column if not exists name text default '',
    add column if not exists class text default '',
    add column if not exists level integer not null default 1,
    add column if not exists hp integer default 10,
    add column if not exists hp_max integer default 10,
    add column if not exists data jsonb not null default '{}'::jsonb,
    add column if not exists created_at timestamptz not null default now(),
    add column if not exists updated_at timestamptz not null default now();

create table if not exists public.dnd_tokens (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null references public.dnd_sessions(id) on delete cascade,
    character_id bigint null references public.characters(id) on delete set null,
    name text not null default 'Token',
    img text default '',
    color text default '#c77dff',
    x integer not null default 420,
    y integer not null default 420,
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.dnd_chat (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null references public.dnd_sessions(id) on delete cascade,
    sender_id uuid null references auth.users(id) on delete set null,
    sender_name text not null default 'Viandante',
    message text not null,
    is_roll boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists public.dnd_session_guests (
    id uuid primary key default gen_random_uuid(),
    session_id uuid not null references public.dnd_sessions(id) on delete cascade,
    user_id uuid not null references auth.users(id) on delete cascade,
    display_name text not null default 'Giocatore',
    role text not null default 'viewer' check (role in ('viewer', 'player')),
    joined_at timestamptz not null default now(),
    last_seen timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (session_id, user_id)
);

alter table public.dnd_session_guests
    add column if not exists updated_at timestamptz not null default now();

create table if not exists public.minigame_rooms (
    id uuid primary key default gen_random_uuid(),
    code text not null unique check (code ~ '^[A-Z0-9]{6}$'),
    host_client_id text not null,
    guest_client_id text default '',
    status text not null default 'waiting' check (status in ('waiting', 'connected', 'closed')),
    data jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    expires_at timestamptz not null default (now() + interval '4 hours')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

create or replace function public.owns_dnd_session(p_session_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.dnd_sessions
        where id = p_session_id
          and user_id = auth.uid()
    );
$$;

create or replace function public.is_dnd_session_guest(p_session_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1
        from public.dnd_session_guests
        join public.dnd_sessions on dnd_sessions.id = dnd_session_guests.session_id
        where dnd_session_guests.session_id = p_session_id
          and dnd_session_guests.user_id = auth.uid()
          and dnd_sessions.share_enabled = true
    );
$$;

revoke all on function public.owns_dnd_session(uuid) from public;
revoke all on function public.is_dnd_session_guest(uuid) from public;
revoke all on function public.owns_dnd_session(uuid) from anon;
revoke all on function public.is_dnd_session_guest(uuid) from anon;
grant execute on function public.owns_dnd_session(uuid) to authenticated;
grant execute on function public.is_dnd_session_guest(uuid) to authenticated;

drop trigger if exists set_dnd_sessions_updated_at on public.dnd_sessions;
create trigger set_dnd_sessions_updated_at
before update on public.dnd_sessions
for each row execute function public.set_updated_at();

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

drop trigger if exists set_user_preferences_updated_at on public.user_preferences;
create trigger set_user_preferences_updated_at
before update on public.user_preferences
for each row execute function public.set_updated_at();

drop trigger if exists set_characters_updated_at on public.characters;
create trigger set_characters_updated_at
before update on public.characters
for each row execute function public.set_updated_at();

drop trigger if exists set_dnd_tokens_updated_at on public.dnd_tokens;
create trigger set_dnd_tokens_updated_at
before update on public.dnd_tokens
for each row execute function public.set_updated_at();

drop trigger if exists set_minigame_rooms_updated_at on public.minigame_rooms;
create trigger set_minigame_rooms_updated_at
before update on public.minigame_rooms
for each row execute function public.set_updated_at();

drop trigger if exists set_dnd_session_guests_updated_at on public.dnd_session_guests;
create trigger set_dnd_session_guests_updated_at
before update on public.dnd_session_guests
for each row execute function public.set_updated_at();

alter table public.dnd_sessions enable row level security;
alter table public.user_profiles enable row level security;
alter table public.user_preferences enable row level security;
alter table public.characters enable row level security;
alter table public.dnd_tokens enable row level security;
alter table public.dnd_chat enable row level security;
alter table public.dnd_session_guests enable row level security;
alter table public.minigame_rooms enable row level security;

grant select, insert, update on public.dnd_sessions to authenticated;
grant select on public.dnd_tokens to authenticated;
grant select on public.dnd_chat to authenticated;
grant select on public.dnd_session_guests to authenticated;
grant select, insert, update on public.minigame_rooms to anon, authenticated;

drop policy if exists "characters_owner_all" on public.characters;
create policy "characters_owner_all"
on public.characters
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_profiles_owner_all" on public.user_profiles;
create policy "user_profiles_owner_all"
on public.user_profiles
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "user_preferences_owner_all" on public.user_preferences;
create policy "user_preferences_owner_all"
on public.user_preferences
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "dnd_sessions_owner_all" on public.dnd_sessions;
create policy "dnd_sessions_owner_all"
on public.dnd_sessions
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "dnd_sessions_guest_read" on public.dnd_sessions;
create policy "dnd_sessions_guest_read"
on public.dnd_sessions
for select
to authenticated
using (public.is_dnd_session_guest(dnd_sessions.id));

drop policy if exists "dnd_tokens_session_owner_all" on public.dnd_tokens;
create policy "dnd_tokens_session_owner_all"
on public.dnd_tokens
for all
using (public.owns_dnd_session(dnd_tokens.session_id))
with check (public.owns_dnd_session(dnd_tokens.session_id));

drop policy if exists "dnd_tokens_guest_read" on public.dnd_tokens;
create policy "dnd_tokens_guest_read"
on public.dnd_tokens
for select
to authenticated
using (public.is_dnd_session_guest(dnd_tokens.session_id));

drop policy if exists "dnd_chat_session_owner_all" on public.dnd_chat;
create policy "dnd_chat_session_owner_all"
on public.dnd_chat
for all
using (public.owns_dnd_session(dnd_chat.session_id))
with check (public.owns_dnd_session(dnd_chat.session_id));

drop policy if exists "dnd_chat_guest_read" on public.dnd_chat;
create policy "dnd_chat_guest_read"
on public.dnd_chat
for select
to authenticated
using (public.is_dnd_session_guest(dnd_chat.session_id));

drop policy if exists "dnd_session_guests_self_or_owner_read" on public.dnd_session_guests;
create policy "dnd_session_guests_self_or_owner_read"
on public.dnd_session_guests
for select
to authenticated
using (
    user_id = auth.uid()
    or public.owns_dnd_session(dnd_session_guests.session_id)
);

drop policy if exists "minigame_rooms_active_read" on public.minigame_rooms;
create policy "minigame_rooms_active_read"
on public.minigame_rooms
for select
to anon, authenticated
using (status <> 'closed' and expires_at > now());

drop policy if exists "minigame_rooms_create" on public.minigame_rooms;
create policy "minigame_rooms_create"
on public.minigame_rooms
for insert
to anon, authenticated
with check (
    length(code) = 6
    and host_client_id <> ''
    and status = 'waiting'
    and expires_at > now()
);

drop policy if exists "minigame_rooms_connect" on public.minigame_rooms;
create policy "minigame_rooms_connect"
on public.minigame_rooms
for update
to anon, authenticated
using (status <> 'closed' and expires_at > now())
with check (
    status in ('waiting', 'connected', 'closed')
    and host_client_id <> ''
    and expires_at > now()
);

create index if not exists dnd_sessions_user_id_idx on public.dnd_sessions(user_id);
create index if not exists dnd_sessions_user_id_system_id_idx on public.dnd_sessions(user_id, system_id);
create index if not exists user_profiles_user_id_idx on public.user_profiles(user_id);
create index if not exists user_preferences_user_id_idx on public.user_preferences(user_id);
create index if not exists dnd_tokens_session_id_idx on public.dnd_tokens(session_id);
create index if not exists dnd_chat_session_id_created_at_idx on public.dnd_chat(session_id, created_at);
create index if not exists dnd_session_guests_session_user_idx on public.dnd_session_guests(session_id, user_id);
create index if not exists characters_user_id_system_id_idx on public.characters(user_id, system_id);
create index if not exists minigame_rooms_code_idx on public.minigame_rooms(code);
create index if not exists minigame_rooms_expires_at_idx on public.minigame_rooms(expires_at);

create or replace function public.join_dnd_session(
    p_session_id uuid,
    p_share_code text,
    p_display_name text default 'Giocatore'
)
returns table(session_id uuid, system_id text, role text)
language plpgsql
security definer
set search_path = public
as $$
declare
    v_user_id uuid := auth.uid();
    v_session public.dnd_sessions%rowtype;
begin
    if v_user_id is null then
        raise exception 'Utente Supabase non autenticato.';
    end if;

    select *
    into v_session
    from public.dnd_sessions
    where id = p_session_id
      and share_enabled = true
      and share_code = p_share_code;

    if not found then
        raise exception 'Invito sessione non valido o disattivato.';
    end if;

    insert into public.dnd_session_guests(session_id, user_id, display_name, role, last_seen)
    values (
        v_session.id,
        v_user_id,
        coalesce(nullif(trim(p_display_name), ''), 'Giocatore'),
        'viewer',
        now()
    )
    on conflict on constraint dnd_session_guests_session_id_user_id_key
    do update set
        display_name = excluded.display_name,
        last_seen = now();

    return query select v_session.id, v_session.system_id, 'viewer'::text;
end;
$$;

revoke all on function public.join_dnd_session(uuid, text, text) from public;
revoke all on function public.join_dnd_session(uuid, text, text) from anon;
grant execute on function public.join_dnd_session(uuid, text, text) to authenticated;

do $$
begin
    alter publication supabase_realtime add table public.dnd_sessions;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.dnd_tokens;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.dnd_chat;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

do $$
begin
    alter publication supabase_realtime add table public.minigame_rooms;
exception
    when duplicate_object then null;
    when undefined_object then null;
end;
$$;

insert into storage.buckets (id, name, public)
values ('vtt_assets', 'vtt_assets', true)
on conflict (id) do update set public = true;

drop policy if exists "vtt_assets_public_read" on storage.objects;
create policy "vtt_assets_public_read"
on storage.objects
for select
using (bucket_id = 'vtt_assets');

drop policy if exists "vtt_assets_owner_write" on storage.objects;
create policy "vtt_assets_owner_write"
on storage.objects
for all
using (bucket_id = 'vtt_assets' and auth.role() = 'authenticated')
with check (bucket_id = 'vtt_assets' and auth.role() = 'authenticated');
