create table if not exists public.user_profiles (
    user_id uuid primary key references auth.users(id) on delete cascade,
    display_name text not null default 'Viandante',
    title text not null default 'Viandante della Taverna',
    avatar_url text not null default '',
    accent text not null default 'amethyst' check (accent in ('amethyst', 'ember', 'emerald')),
    glow boolean not null default true,
    compact_cards boolean not null default false,
    updated_at timestamptz not null default now()
);

create table if not exists public.user_preferences (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    key text not null check (char_length(key) between 1 and 100),
    value jsonb not null default 'null'::jsonb,
    updated_at timestamptz not null default now(),
    unique (user_id, key)
);

create index if not exists user_preferences_user_id_idx
    on public.user_preferences (user_id);

alter table public.user_profiles enable row level security;
alter table public.user_preferences enable row level security;

grant select, insert, update on table public.user_profiles to authenticated;
grant select, insert, update, delete on table public.user_preferences to authenticated;
grant select, insert, update, delete on table public.user_profiles to service_role;
grant select, insert, update, delete on table public.user_preferences to service_role;
grant usage, select on sequence public.user_preferences_id_seq to authenticated, service_role;

do $$
begin
    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'user_profiles_select_own'
    ) then
        create policy user_profiles_select_own
            on public.user_profiles for select
            using ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'user_profiles_insert_own'
    ) then
        create policy user_profiles_insert_own
            on public.user_profiles for insert
            with check ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_profiles' and policyname = 'user_profiles_update_own'
    ) then
        create policy user_profiles_update_own
            on public.user_profiles for update
            using ((select auth.uid()) = user_id)
            with check ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_preferences' and policyname = 'user_preferences_select_own'
    ) then
        create policy user_preferences_select_own
            on public.user_preferences for select
            using ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_preferences' and policyname = 'user_preferences_insert_own'
    ) then
        create policy user_preferences_insert_own
            on public.user_preferences for insert
            with check ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_preferences' and policyname = 'user_preferences_update_own'
    ) then
        create policy user_preferences_update_own
            on public.user_preferences for update
            using ((select auth.uid()) = user_id)
            with check ((select auth.uid()) = user_id);
    end if;

    if not exists (
        select 1 from pg_policies
        where schemaname = 'public' and tablename = 'user_preferences' and policyname = 'user_preferences_delete_own'
    ) then
        create policy user_preferences_delete_own
            on public.user_preferences for delete
            using ((select auth.uid()) = user_id);
    end if;
end
$$;

notify pgrst, 'reload schema';
